language: python
sudo: false
python:
    - "3.5"

install:
    # Base requirements
    - bash install-dependencies.sh -t
    - source activate scenarios
    # Install shakemap-scenarios
    - python setup.py install
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    # Put conf file in home directory
    - cp data/scenarios.conf ~/.
script:
    - export PYTHONPATH="."
    - py.test --cov=.
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
